name: Tag Merge Commit
on:
  pull_request:
    types:  [closed]
    branches: [main]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          WITH_V: false
          PRERELEASE: true

  goreleaser:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: '>=1.20.0'
     # - name: Clear module cache
     #   run: go clean -modcache
     # - name: Clear build cache
     #   run: go clean -cache
     - name: Run GoReleaser
       uses: goreleaser/goreleaser-action@v5
       with:
         distribution: goreleaser
         version: ${{ env.GITHUB_REF_NAME }}
         args: release --clean
       env:
         GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
